name: flutter_pdf_text
description: This plugin for Flutter allows you to read the text content of PDF documents and convert it into strings. It works on iOS and Android.
version: 0.6.0
homepage: https://github.com/FaFre/flutter-pdf-text

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  path: ^1.8.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any

flutter:
  plugin:
    platforms:
      android:
        package: dev.aluc.pdf_text
        pluginClass: PdfTextPlugin
      ios:
        pluginClass: PdfTextPlugin
